### ISSUE TITLE
Text about the description of the CanaryRelease & CanaryReleaseStage Process are the same

### ISSUE THREAD

**Issue by cmoulliard** [fabric8io/fabric8-jenkinsfile-library#4]
Canary Release

![screenshot 2016-12-07 14 06 07](https://cloud.githubusercontent.com/assets/463790/20968922/f69ccc06-bc86-11e6-89cb-9f45e8a749ba.png)

Canary Release & Stage

![screenshot 2016-12-07 14 06 13](https://cloud.githubusercontent.com/assets/463790/20968928/fb129220-bc86-11e6-9982-1464279550fa.png)

**Comment by jstrachan** [comment]
think this is now fixed:

* https://github.com/fabric8io/fabric8-jenkinsfile-library/tree/master/maven/Release/ReadMe.md
* https://github.com/fabric8io/fabric8-jenkinsfile-library/tree/master/maven/ReleaseAndStage/ReadMe.md
* https://github.com/fabric8io/fabric8-jenkinsfile-library/blob/master/maven/ReleaseStageApproveAndPromote/ReadMe.md
